FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="$PATH:/root/.local/bin"

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

ENV POETRY_VIRTUALENVS_PATH=/usr/src/.venv \
    POETRY_VIRTUALENVS_IN_PROJECT=0
RUN poetry install --only main --no-root --no-cache

COPY manage.py /app/
COPY apps /app/apps
COPY config /app/config
